// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Pokedex.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220708001613_NewPokemon1")]
    partial class NewPokemon1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Moves", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Effect")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartPP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("Pokemon", b =>
                {
                    b.Property<int>("DexNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Base_ATK")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Base_DEF")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Base_HP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Base_SPC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Base_SPD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Catch_Rate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Japanese_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RedBlueDex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type2")
                        .HasColumnType("TEXT");

                    b.Property<string>("YellowDex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DexNum");

                    b.ToTable("Pokemon");

                    b.HasData(
                        new
                        {
                            DexNum = 1,
                            Base_ATK = 49,
                            Base_DEF = 49,
                            Base_HP = 45,
                            Base_SPC = 65,
                            Base_SPD = 45,
                            Catch_Rate = 45,
                            Japanese_Name = "フシギダネ",
                            Name = "Bulbasaur",
                            RedBlueDex = "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.",
                            Type1 = "Grass",
                            Type2 = "Poison",
                            YellowDex = "It can go for days without eating a single morsel. In the bulb on its back, it stores energy."
                        },
                        new
                        {
                            DexNum = 2,
                            Base_ATK = 62,
                            Base_DEF = 63,
                            Base_HP = 60,
                            Base_SPC = 80,
                            Base_SPD = 60,
                            Catch_Rate = 45,
                            Japanese_Name = "フシギソウ",
                            Name = "Ivysaur",
                            RedBlueDex = "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.",
                            Type1 = "Grass",
                            Type2 = "Poison",
                            YellowDex = "It can go for days without eating a single morsel. In the bulb on its back, it stores energy."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
