// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Pokedex.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220724223318_NewMoves2")]
    partial class NewMoves2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Moves", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Effect")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartPP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Moves");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Accuracy = 100,
                            Effect = "User recovers half the HP inflicted on opponent.",
                            Name = "Absorb",
                            Power = 20,
                            StartPP = 20,
                            Type = "Grass"
                        },
                        new
                        {
                            ID = 2,
                            Accuracy = 100,
                            Effect = "Has a 33% chance to lower the target's Defense by 1 stage.",
                            Name = "Acid",
                            Power = 40,
                            StartPP = 30,
                            Type = "Poison"
                        },
                        new
                        {
                            ID = 3,
                            Accuracy = 100,
                            Effect = "Raises the user's Defense by 2 stages.",
                            Name = "Acid Armor",
                            Power = 0,
                            StartPP = 40,
                            Type = "Poison"
                        },
                        new
                        {
                            ID = 4,
                            Accuracy = 100,
                            Effect = "Raises the user's Speed by 2 stages.",
                            Name = "Agility",
                            Power = 0,
                            StartPP = 30,
                            Type = "Psychic"
                        },
                        new
                        {
                            ID = 5,
                            Accuracy = 100,
                            Effect = "Raises the user's Special by 2 stages.",
                            Name = "Amnesia",
                            Power = 0,
                            StartPP = 20,
                            Type = "Psychic"
                        },
                        new
                        {
                            ID = 6,
                            Accuracy = 100,
                            Effect = "Has a 33% chance to lower the target's Attack by 1 stage.",
                            Name = "Aurora Beam",
                            Power = 65,
                            StartPP = 20,
                            Type = "Ice"
                        },
                        new
                        {
                            ID = 7,
                            Accuracy = 85,
                            Effect = "Hits two to five times. Has a 3/8 chance to hit two or three times, and a 1/8 chance to hit four or five times. Damage is calculated once for the first hit and used for every hit. If one of the hits breaks the target's substitute, the move ends.",
                            Name = "Barrage",
                            Power = 15,
                            StartPP = 20,
                            Type = "Normal"
                        },
                        new
                        {
                            ID = 8,
                            Accuracy = 100,
                            Effect = "Raises the user's Defense by 2 stages.",
                            Name = "Barrier",
                            Power = 0,
                            StartPP = 30,
                            Type = "Psychic"
                        },
                        new
                        {
                            ID = 9,
                            Accuracy = 100,
                            Effect = "The user spends two to three turns locked into this move and then, on the second or third turn after using this move, the user attacks the opponent, inflicting double the damage in HP it lost during those turns. This move ignores type immunity and cannot be avoided even if the target is using Dig or Fly. The user can choose to switch out during the effect. If the user switches out or is prevented from moving during this move's use, the effect ends. During the effect, if the opposing Pokemon switched out or uses Confuse Ray, Conversion, Focus Energy, Glare, Haze, Leech Seed, Light Screen, Mimic, Mist, Poison Gas, Poison Powder, Recover, Reflect, Rest, Soft-Boiled, Splash, Stun Spore, Substitute, Supersonic, Teleport, Thunder Wave, Toxic, or Transform, the previous damage dealt to the user will be added to the total.",
                            Name = "Bide",
                            Power = 0,
                            StartPP = 10,
                            Type = "Normal"
                        },
                        new
                        {
                            ID = 10,
                            Accuracy = 85,
                            Effect = "The user spends two to five turns using this move. Has a 3/8 chance to last two or three turns, and a 1/8 chance to last four or five turns. The damage calculated for the first turn is used for every other turn. The user cannot select a move and the target cannot execute a move during the effect, but both may switch out. If the user switches out, the target remains unable to execute a move during that turn. If the target switches out, the user uses this move automatically, and if it had 0 PP at the time, it becomes 63. If the user or the target switches out, or the user is prevented from moving, the effect ends. This move can prevent the target from moving even if it has type immunity but will not deal damage",
                            Name = "Bind",
                            Power = 15,
                            StartPP = 20,
                            Type = "Normal"
                        },
                        new
                        {
                            ID = 11,
                            Accuracy = 100,
                            Effect = "Has a 10% chance to make the target flinch.",
                            Name = "Bite",
                            Power = 60,
                            StartPP = 25,
                            Type = "Normal"
                        },
                        new
                        {
                            ID = 12,
                            Accuracy = 90,
                            Effect = "Has a 10% chance to freeze the target.",
                            Name = "Blizzard",
                            Power = 120,
                            StartPP = 5,
                            Type = "Ice"
                        },
                        new
                        {
                            ID = 13,
                            Accuracy = 100,
                            Effect = "Has a 30% chance to paralyze the target.",
                            Name = "Body Slam",
                            Power = 85,
                            StartPP = 15,
                            Type = "Normal"
                        },
                        new
                        {
                            ID = 14,
                            Accuracy = 85,
                            Effect = "Has a 10% chance to make the target flinch.",
                            Name = "Bone Club",
                            Power = 65,
                            StartPP = 20,
                            Type = "Ground"
                        },
                        new
                        {
                            ID = 15,
                            Accuracy = 90,
                            Effect = "Hits twice. If the first hit breaks the target's substitute, the move ends.",
                            Name = "Bonemerang",
                            Power = 50,
                            StartPP = 10,
                            Type = "Ground"
                        },
                        new
                        {
                            ID = 16,
                            Accuracy = 100,
                            Effect = "Has a 33% chance to lower the target's Speed by 1 stage.",
                            Name = "Bubble",
                            Power = 20,
                            StartPP = 30,
                            Type = "Water"
                        },
                        new
                        {
                            ID = 17,
                            Accuracy = 100,
                            Effect = "Has a 33% chance to lower the target's Speed by 1 stage.",
                            Name = "Bubble Beam",
                            Power = 65,
                            StartPP = 20,
                            Type = "Water"
                        },
                        new
                        {
                            ID = 18,
                            Accuracy = 75,
                            Effect = "The user spends two to five turns using this move. Has a 3/8 chance to last two or three turns, and a 1/8 chance to last four or five turns. The damage calculated for the first turn is used for every other turn. The user cannot select a move and the target cannot execute a move during the effect, but both may switch out. If the user switches out, the target remains unable to execute a move during that turn. If the target switches out, the user uses this move automatically, and if it had 0 PP at the time, it becomes 63. If the user or the target switches out, or the user is prevented from moving, the effect ends. This move can prevent the target from moving even if it has type immunity but will not deal damage",
                            Name = "Clamp",
                            Power = 35,
                            StartPP = 10,
                            Type = "Water"
                        },
                        new
                        {
                            ID = 19,
                            Accuracy = 85,
                            Effect = "Hits two to five times. Has a 3/8 chance to hit two or three times, and a 1/8 chance to hit four or five times. Damage is calculated once for the first hit and used for every hit. If one of the hits breaks the target's substitute, the move ends.",
                            Name = "Comet Punch",
                            Power = 18,
                            StartPP = 15,
                            Type = "Normal"
                        },
                        new
                        {
                            ID = 20,
                            Accuracy = 100,
                            Effect = "Causes the target to become confused.",
                            Name = "Confuse Ray",
                            Power = 0,
                            StartPP = 10,
                            Type = "Ghost"
                        });
                });

            modelBuilder.Entity("Pokemon", b =>
                {
                    b.Property<int>("DexNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Base_ATK")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Base_DEF")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Base_HP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Base_SPC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Base_SPD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Catch_Rate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Japanese_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RedBlueDex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type2")
                        .HasColumnType("TEXT");

                    b.Property<string>("YellowDex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DexNum");

                    b.ToTable("Pokemon");

                    b.HasData(
                        new
                        {
                            DexNum = 1,
                            Base_ATK = 49,
                            Base_DEF = 49,
                            Base_HP = 45,
                            Base_SPC = 65,
                            Base_SPD = 45,
                            Catch_Rate = 45,
                            Japanese_Name = "フシギダネ",
                            Name = "Bulbasaur",
                            RedBlueDex = "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.",
                            Type1 = "Grass",
                            Type2 = "Poison",
                            YellowDex = "It can go for days without eating a single morsel. In the bulb on its back, it stores energy."
                        },
                        new
                        {
                            DexNum = 2,
                            Base_ATK = 62,
                            Base_DEF = 63,
                            Base_HP = 60,
                            Base_SPC = 80,
                            Base_SPD = 60,
                            Catch_Rate = 45,
                            Japanese_Name = "フシギソウ",
                            Name = "Ivysaur",
                            RedBlueDex = "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.",
                            Type1 = "Grass",
                            Type2 = "Poison",
                            YellowDex = "It can go for days without eating a single morsel. In the bulb on its back, it stores energy."
                        },
                        new
                        {
                            DexNum = 3,
                            Base_ATK = 82,
                            Base_DEF = 83,
                            Base_HP = 80,
                            Base_SPC = 100,
                            Base_SPD = 80,
                            Catch_Rate = 45,
                            Japanese_Name = "フシギバナ",
                            Name = "Venusaur",
                            RedBlueDex = "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
                            Type1 = "Grass",
                            Type2 = "Poison",
                            YellowDex = "The flower on its back catches the sun's rays. The sunlight is then absorbed and used for energy."
                        },
                        new
                        {
                            DexNum = 4,
                            Base_ATK = 52,
                            Base_DEF = 43,
                            Base_HP = 39,
                            Base_SPC = 50,
                            Base_SPD = 65,
                            Catch_Rate = 45,
                            Japanese_Name = "ヒトカゲ",
                            Name = "Charmander",
                            RedBlueDex = "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.",
                            Type1 = "Fire",
                            YellowDex = "The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places."
                        },
                        new
                        {
                            DexNum = 5,
                            Base_ATK = 64,
                            Base_DEF = 58,
                            Base_HP = 58,
                            Base_SPC = 65,
                            Base_SPD = 80,
                            Catch_Rate = 45,
                            Japanese_Name = "リザード",
                            Name = "Charmeleon",
                            RedBlueDex = "When it swings its burning tail, it elevates the temperature to unbearably high levels.",
                            Type1 = "Fire",
                            YellowDex = "Tough fights could excite this Pokémon. When excited, it may blow out bluish-white flames."
                        },
                        new
                        {
                            DexNum = 6,
                            Base_ATK = 84,
                            Base_DEF = 78,
                            Base_HP = 78,
                            Base_SPC = 85,
                            Base_SPD = 100,
                            Catch_Rate = 45,
                            Japanese_Name = "リザードン",
                            Name = "Charizard",
                            RedBlueDex = "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.",
                            Type1 = "Fire",
                            YellowDex = "When expelling a blast of super hot fire, the red flame at the tip of its tail burns more intensely."
                        },
                        new
                        {
                            DexNum = 7,
                            Base_ATK = 48,
                            Base_DEF = 65,
                            Base_HP = 44,
                            Base_SPC = 50,
                            Base_SPD = 43,
                            Catch_Rate = 45,
                            Japanese_Name = "ゼニガメ",
                            Name = "Squirtle",
                            RedBlueDex = "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.",
                            Type1 = "Water",
                            YellowDex = "Shoots water at prey while in the water. Withdraws into its shell when in danger."
                        },
                        new
                        {
                            DexNum = 8,
                            Base_ATK = 63,
                            Base_DEF = 80,
                            Base_HP = 59,
                            Base_SPC = 65,
                            Base_SPD = 58,
                            Catch_Rate = 45,
                            Japanese_Name = "カメール",
                            Name = "Wartortle",
                            RedBlueDex = "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.",
                            Type1 = "Water",
                            YellowDex = "When tapped, this Pokémon will pull in its head, but its tail will still stick out a little bit."
                        },
                        new
                        {
                            DexNum = 9,
                            Base_ATK = 83,
                            Base_DEF = 100,
                            Base_HP = 79,
                            Base_SPC = 85,
                            Base_SPD = 78,
                            Catch_Rate = 45,
                            Japanese_Name = "カメックス",
                            Name = "Blastoise",
                            RedBlueDex = "A brutal Pokémon with pressurized water jets on its shell. They are used for high speed tackles.",
                            Type1 = "Water",
                            YellowDex = "Once it takes aim at its enemy, it blasts out water with even more force than a fire hose."
                        },
                        new
                        {
                            DexNum = 10,
                            Base_ATK = 30,
                            Base_DEF = 35,
                            Base_HP = 45,
                            Base_SPC = 20,
                            Base_SPD = 45,
                            Catch_Rate = 255,
                            Japanese_Name = "キャタピー",
                            Name = "Caterpie",
                            RedBlueDex = "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
                            Type1 = "Bug",
                            YellowDex = "If you touch the feeler on top of its head, it will release a horrible stink to protect itself."
                        },
                        new
                        {
                            DexNum = 11,
                            Base_ATK = 20,
                            Base_DEF = 55,
                            Base_HP = 50,
                            Base_SPC = 25,
                            Base_SPD = 30,
                            Catch_Rate = 120,
                            Japanese_Name = "トランセル",
                            Name = "Metapod",
                            RedBlueDex = "This Pokémon is vulnerable to attack while its shell is soft, exposing its weak and tender body.",
                            Type1 = "Bug",
                            YellowDex = "	Hardens its shell to protect itself. However, a large impact may cause it to pop out of its shell."
                        },
                        new
                        {
                            DexNum = 12,
                            Base_ATK = 45,
                            Base_DEF = 50,
                            Base_HP = 60,
                            Base_SPC = 80,
                            Base_SPD = 75,
                            Catch_Rate = 45,
                            Japanese_Name = "バタフリー",
                            Name = "Butterfree",
                            RedBlueDex = "In battle, it flaps its wings at high speed to release highly toxic dust into the air.",
                            Type1 = "Bug",
                            Type2 = "Flying",
                            YellowDex = "Its wings, covered with poisonous powders, repel water. This allows it to fly in the rain."
                        },
                        new
                        {
                            DexNum = 13,
                            Base_ATK = 35,
                            Base_DEF = 30,
                            Base_HP = 40,
                            Base_SPC = 20,
                            Base_SPD = 50,
                            Catch_Rate = 255,
                            Japanese_Name = "ビードル",
                            Name = "Weedle",
                            RedBlueDex = "Often found in forests, eating leaves. It has a sharp venomous stinger on its head.",
                            Type1 = "Bug",
                            Type2 = "Poison",
                            YellowDex = "Beware of the sharp stinger on its head. It hides in grass and bushes where it eats leaves."
                        },
                        new
                        {
                            DexNum = 14,
                            Base_ATK = 25,
                            Base_DEF = 50,
                            Base_HP = 45,
                            Base_SPC = 25,
                            Base_SPD = 35,
                            Catch_Rate = 120,
                            Japanese_Name = "コクーン",
                            Name = "Kakuna",
                            RedBlueDex = "Almost incapable of moving, this Pokémon can only harden its shell to protect itself from predators.",
                            Type1 = "Bug",
                            Type2 = "Poison",
                            YellowDex = "Able to move only slightly. When endangered, it may stick out its stinger and poison its enemy."
                        },
                        new
                        {
                            DexNum = 15,
                            Base_ATK = 80,
                            Base_DEF = 40,
                            Base_HP = 65,
                            Base_SPC = 45,
                            Base_SPD = 75,
                            Catch_Rate = 45,
                            Japanese_Name = "スピアー",
                            Name = "Beedrill",
                            RedBlueDex = "Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.",
                            Type1 = "Bug",
                            Type2 = "Poison",
                            YellowDex = "It has 3 poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly."
                        },
                        new
                        {
                            DexNum = 16,
                            Base_ATK = 45,
                            Base_DEF = 40,
                            Base_HP = 40,
                            Base_SPC = 35,
                            Base_SPD = 56,
                            Catch_Rate = 255,
                            Japanese_Name = "ポッポ",
                            Name = "Pidgey",
                            RedBlueDex = "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.",
                            Type1 = "Normal",
                            Type2 = "Flying",
                            YellowDex = "Very docile. If attacked, it will often kick up sand to protect itself rather than fight back."
                        },
                        new
                        {
                            DexNum = 17,
                            Base_ATK = 60,
                            Base_DEF = 55,
                            Base_HP = 63,
                            Base_SPC = 50,
                            Base_SPD = 71,
                            Catch_Rate = 120,
                            Japanese_Name = "ピジョン",
                            Name = "Pidgeotto",
                            RedBlueDex = "Very protective of its sprawling territorial area, this Pokémon will fiercely peck at any intruder.",
                            Type1 = "Normal",
                            Type2 = "Flying",
                            YellowDex = "This Pokémon is full of vitality. It constantly flies around its large territory in search of prey."
                        },
                        new
                        {
                            DexNum = 18,
                            Base_ATK = 80,
                            Base_DEF = 75,
                            Base_HP = 83,
                            Base_SPC = 70,
                            Base_SPD = 91,
                            Catch_Rate = 45,
                            Japanese_Name = "ピジョット",
                            Name = "Pidgeot",
                            RedBlueDex = "When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp.",
                            Type1 = "Normal",
                            Type2 = "Flying",
                            YellowDex = "This Pokémon flies at Mach 2 speed, seeking prey. Its large talons are feared as wicked weapons."
                        },
                        new
                        {
                            DexNum = 19,
                            Base_ATK = 56,
                            Base_DEF = 35,
                            Base_HP = 30,
                            Base_SPC = 25,
                            Base_SPD = 72,
                            Catch_Rate = 255,
                            Japanese_Name = "コラッタ",
                            Name = "Rattata",
                            RedBlueDex = "Bites anything when it attacks. Small and very quick, it is a common sight in many places.",
                            Type1 = "Normal",
                            YellowDex = "Will chew on anything with its fangs. If you see one, it is certain that 40 more live in the area."
                        },
                        new
                        {
                            DexNum = 20,
                            Base_ATK = 81,
                            Base_DEF = 60,
                            Base_HP = 55,
                            Base_SPC = 50,
                            Base_SPD = 97,
                            Catch_Rate = 127,
                            Japanese_Name = "ラッタ",
                            Name = "Raticate",
                            RedBlueDex = "It uses its whiskers to maintain its balance. It apparently slows down if they are cut off.",
                            Type1 = "Normal",
                            YellowDex = "Its hind feet are webbed. They act as flippers, so it can swim in rivers and hunt for prey."
                        },
                        new
                        {
                            DexNum = 21,
                            Base_ATK = 60,
                            Base_DEF = 30,
                            Base_HP = 40,
                            Base_SPC = 31,
                            Base_SPD = 70,
                            Catch_Rate = 255,
                            Japanese_Name = "オニスズメ",
                            Name = "Spearow",
                            RedBlueDex = "Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne.",
                            Type1 = "Normal",
                            Type2 = "Flying",
                            YellowDex = "Inept at flying high. However, it can fly around very fast to protect its territory."
                        },
                        new
                        {
                            DexNum = 22,
                            Base_ATK = 90,
                            Base_DEF = 65,
                            Base_HP = 65,
                            Base_SPC = 61,
                            Base_SPD = 100,
                            Catch_Rate = 90,
                            Japanese_Name = "オニドリル",
                            Name = "Fearow",
                            RedBlueDex = "With its huge and magnificent wings, it can keep aloft without ever having to land for rest.",
                            Type1 = "Normal",
                            Type2 = "Flying",
                            YellowDex = "A Pokémon that dates back many years. If it senses danger, it flies high and away, instantly."
                        },
                        new
                        {
                            DexNum = 23,
                            Base_ATK = 60,
                            Base_DEF = 44,
                            Base_HP = 35,
                            Base_SPC = 40,
                            Base_SPD = 55,
                            Catch_Rate = 255,
                            Japanese_Name = "アーボ",
                            Name = "Ekans",
                            RedBlueDex = "Moves silently and stealthily. Eats the eggs of birds, such as Pidgey and Spearow, whole.",
                            Type1 = "Poison",
                            YellowDex = "The older it gets, the longer it grows. At night, it wraps its long body around tree branches to rest."
                        },
                        new
                        {
                            DexNum = 24,
                            Base_ATK = 85,
                            Base_DEF = 69,
                            Base_HP = 60,
                            Base_SPC = 65,
                            Base_SPD = 80,
                            Catch_Rate = 90,
                            Japanese_Name = "アーボック",
                            Name = "Arbok",
                            RedBlueDex = "It is rumored that the ferocious warning markings on its belly differ from area to area.",
                            Type1 = "Poison",
                            YellowDex = "The frightening patterns on its belly have been studied. Six variations have been confirmed."
                        },
                        new
                        {
                            DexNum = 25,
                            Base_ATK = 55,
                            Base_DEF = 30,
                            Base_HP = 35,
                            Base_SPC = 50,
                            Base_SPD = 90,
                            Catch_Rate = 190,
                            Japanese_Name = "ピカチュウ",
                            Name = "Pikachu",
                            RedBlueDex = "When several of these Pokémon gather, their electricity could build and cause lightning storms.",
                            Type1 = "Electric",
                            YellowDex = "It keeps its tail raised to monitor its surroundings. If you yank its tail, it will try to bite you."
                        },
                        new
                        {
                            DexNum = 26,
                            Base_ATK = 90,
                            Base_DEF = 55,
                            Base_HP = 60,
                            Base_SPC = 90,
                            Base_SPD = 100,
                            Catch_Rate = 75,
                            Japanese_Name = "ライチュウ",
                            Name = "Raichu",
                            RedBlueDex = "Its long tail serves as a ground to protect itself from its own high voltage power.",
                            Type1 = "Electric",
                            YellowDex = "When electricity builds up inside its body, it becomes feisty. It also glows in the dark."
                        },
                        new
                        {
                            DexNum = 27,
                            Base_ATK = 75,
                            Base_DEF = 85,
                            Base_HP = 50,
                            Base_SPC = 30,
                            Base_SPD = 40,
                            Catch_Rate = 255,
                            Japanese_Name = "サンド",
                            Name = "Sandshrew",
                            RedBlueDex = "Burrows deep underground in arid locations far from water. It only emerges to hunt for food.",
                            Type1 = "Ground",
                            YellowDex = "Its body is dry. When it gets cold at night, its hide is said to become coated with a fine dew."
                        },
                        new
                        {
                            DexNum = 28,
                            Base_ATK = 100,
                            Base_DEF = 110,
                            Base_HP = 75,
                            Base_SPC = 55,
                            Base_SPD = 65,
                            Catch_Rate = 90,
                            Japanese_Name = "サンドパン",
                            Name = "Sandslash",
                            RedBlueDex = "Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.",
                            Type1 = "Ground",
                            YellowDex = "It is skilled at slashing enemies with its claws. If broken, they start to grow back in a day."
                        },
                        new
                        {
                            DexNum = 29,
                            Base_ATK = 47,
                            Base_DEF = 52,
                            Base_HP = 55,
                            Base_SPC = 40,
                            Base_SPD = 41,
                            Catch_Rate = 235,
                            Japanese_Name = "ニドラン♀",
                            Name = "Nidoran♀",
                            RedBlueDex = "Although small, its venomous barbs render this Pokémon dangerous. The female has smaller horns.",
                            Type1 = "Poison",
                            YellowDex = "A mild-mannered Pokémon that does not like to fight. Beware, its small horns secrete venom."
                        },
                        new
                        {
                            DexNum = 30,
                            Base_ATK = 62,
                            Base_DEF = 67,
                            Base_HP = 70,
                            Base_SPC = 55,
                            Base_SPD = 56,
                            Catch_Rate = 120,
                            Japanese_Name = "ニドリーナ",
                            Name = "Nidorina",
                            RedBlueDex = "The female's horn develops slowly. Prefers physical attacks such as clawing and biting.",
                            Type1 = "Poison",
                            YellowDex = "When resting deep in its burrow, its thorns always retract. This is proof that it is relaxed."
                        },
                        new
                        {
                            DexNum = 31,
                            Base_ATK = 82,
                            Base_DEF = 87,
                            Base_HP = 90,
                            Base_SPC = 75,
                            Base_SPD = 76,
                            Catch_Rate = 45,
                            Japanese_Name = "ニドクイン",
                            Name = "Nidoqueen",
                            RedBlueDex = "Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.",
                            Type1 = "Poison",
                            Type2 = "Ground",
                            YellowDex = "Tough scales cover the sturdy body of this Pokémon. It appears that the scales grow in cycles."
                        },
                        new
                        {
                            DexNum = 32,
                            Base_ATK = 57,
                            Base_DEF = 40,
                            Base_HP = 46,
                            Base_SPC = 40,
                            Base_SPD = 50,
                            Catch_Rate = 235,
                            Japanese_Name = "“ニドラン♂",
                            Name = "Nidoran♂",
                            RedBlueDex = "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.",
                            Type1 = "Poison",
                            YellowDex = "Its large ears are always kept upright. If it senses danger, it will attack with a poisonous sting."
                        },
                        new
                        {
                            DexNum = 33,
                            Base_ATK = 72,
                            Base_DEF = 57,
                            Base_HP = 61,
                            Base_SPC = 55,
                            Base_SPD = 65,
                            Catch_Rate = 120,
                            Japanese_Name = "“ニドリーノ",
                            Name = "Nidorino",
                            RedBlueDex = "An aggressive Pokémon that is quick to attack. The horn on its head secretes a powerful venom.",
                            Type1 = "Poison",
                            YellowDex = "Its horns contain venom. If they are stabbed into an enemy, the impact makes the poison leak out."
                        },
                        new
                        {
                            DexNum = 34,
                            Base_ATK = 92,
                            Base_DEF = 77,
                            Base_HP = 81,
                            Base_SPC = 75,
                            Base_SPD = 85,
                            Catch_Rate = 45,
                            Japanese_Name = "“ニドキング",
                            Name = "Nidoking",
                            RedBlueDex = "It uses its powerful tail in battle to smash, constrict, then break the prey's bones.",
                            Type1 = "Poison",
                            Type2 = "Ground",
                            YellowDex = "Its steel-like hide adds to its powerful tackle. Its horns are so hard, they can pierce a diamond."
                        },
                        new
                        {
                            DexNum = 35,
                            Base_ATK = 45,
                            Base_DEF = 48,
                            Base_HP = 70,
                            Base_SPC = 60,
                            Base_SPD = 35,
                            Catch_Rate = 150,
                            Japanese_Name = "ピッピ",
                            Name = "Clefairy",
                            RedBlueDex = "Its magical and cute appeal has many admirers. It is rare and found only in certain areas.",
                            Type1 = "Normal",
                            YellowDex = "Adored for their cute looks and playfulness. They are thought to be rare, as they do not appear often."
                        },
                        new
                        {
                            DexNum = 36,
                            Base_ATK = 70,
                            Base_DEF = 73,
                            Base_HP = 95,
                            Base_SPC = 85,
                            Base_SPD = 60,
                            Catch_Rate = 25,
                            Japanese_Name = "ピクシー",
                            Name = "Clefable",
                            RedBlueDex = "Its magical and cute appeal has many admirers. It is rare and found only in certain areas.",
                            Type1 = "Normal",
                            YellowDex = "Adored for their cute looks and playfulness. They are thought to be rare, as they do not appear often."
                        },
                        new
                        {
                            DexNum = 37,
                            Base_ATK = 41,
                            Base_DEF = 40,
                            Base_HP = 38,
                            Base_SPC = 65,
                            Base_SPD = 65,
                            Catch_Rate = 190,
                            Japanese_Name = "ロコン",
                            Name = "Vulpix",
                            RedBlueDex = "At the time of birth, it has just one tail. The tail splits from its tip as it grows older.",
                            Type1 = "Fire",
                            YellowDex = "Both its fur and its tails are beautiful. As it grows, the tails split and form more tails."
                        },
                        new
                        {
                            DexNum = 38,
                            Base_ATK = 76,
                            Base_DEF = 75,
                            Base_HP = 73,
                            Base_SPC = 100,
                            Base_SPD = 100,
                            Catch_Rate = 75,
                            Japanese_Name = "キュウコン",
                            Name = "Ninetales",
                            RedBlueDex = "Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.",
                            Type1 = "Fire",
                            YellowDex = "According to an enduring legend, 9 noble saints were united and reincarnated as this Pokémon."
                        },
                        new
                        {
                            DexNum = 39,
                            Base_ATK = 45,
                            Base_DEF = 20,
                            Base_HP = 115,
                            Base_SPC = 25,
                            Base_SPD = 20,
                            Catch_Rate = 170,
                            Japanese_Name = "プリン",
                            Name = "Jigglypuff",
                            RedBlueDex = "When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.",
                            Type1 = "Normal",
                            YellowDex = "Uses its alluring eyes to enrapture its foe. It then sings a pleasing melody that lulls the foe to sleep."
                        },
                        new
                        {
                            DexNum = 40,
                            Base_ATK = 70,
                            Base_DEF = 45,
                            Base_HP = 140,
                            Base_SPC = 50,
                            Base_SPD = 45,
                            Catch_Rate = 50,
                            Japanese_Name = "プクリン",
                            Name = "Wigglytuff",
                            RedBlueDex = "The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.",
                            Type1 = "Normal",
                            YellowDex = "Its body is full of elasticity. By inhaling deeply, it can continue to inflate itself without limit."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
